import './globals.css'
import { Inter } from 'next/font/google'
import { NextAuthProvider } from "@/app/providers";
import { ENV } from '@/lib/envSchema';
import GoogleTagManager from '@/components/GoogleTagManager';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {ENV.GTM_CONTAINER_ID && <GoogleTagManager Id={ENV.GTM_CONTAINER_ID} />}
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  )
}
